apiVersion: v1
kind: Pod
metadata:
  name: app-color-blue
  labels:
    app: web
spec:
  containers:
    - name: app-color-blue 
      image: mmumshad/simple-webapp-color
      ports:
       - containerPort: 8080
      env:
       - name: APP_COLOR
         value: blue
