apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: mysql
spec:
  containers:
    - image: mysql
      name: mysql
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: password
       - name: MYSQL_DATABASE
         value: eazytraining
       - name: MYSQL_USER	
         value: eazy
       - name: MYSQL_PASSWORD
         value: eazy
      ports:
       - name: mysql
         containerPort: 3306
      volumeMounts:
       - name: data-mysql
         mountPath: /var/lib/mysql
  volumes:
       - name: data-mysql
         hostPath:
          path: /data-volume #s'assurer de creer le dossier data-volume en local
          type: Directory
